### ISSUE TITLE
ROI Contour example image blank

### ISSUE THREAD

**Issue by dmreagan** [fury-gl/fury-website#2]
The [example page](http://fury.gl/dev/auto_examples/viz_roi_contour.html#sphx-glr-auto-examples-viz-roi-contour-py) displays a blank image. When I run the example on my own, it renders without issue.

It should look like this:
![contour_from_roi_tutorial](https://user-images.githubusercontent.com/6951528/49885119-77523280-fe04-11e8-9f19-49522773843b.png)

**Comment by skoudoro** [comment]
fixed by https://github.com/fury-gl/fury/pull/50, closing
